spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/newsdb
    username: postgres
    password: bluetree
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  storage:
    type: minio
    minio:
      endpoint: http://localhost:9000
      accessKey: fnL9OJdweQGwBxfMsK5M
      secretKey: Uy4ErfdYF8zcv4yyVAyxLRuwfGZcnATymisadjjM
      bucket: happynews-bucket
