spring:
  datasource:
    url: jdbc:postgresql://happynewsdb.cly06a0o2a0m.us-east-1.rds.amazonaws.com:5432/happynewsdb
    username: postgres
    password: bluetree
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  storage:
    type: s3
    s3:
      region: us-east-1
      bucket: happynews-bucket
